### ISSUE TITLE
Impact of training statistics on performance

### ISSUE THREAD

**Issue by TarekHC** [cta-observatory/iact_event_types#11]
Hi Orel, 

We need to evaluate the impact of the training statistics on performance. 

Going to the extreme: If with a 5% of the MC we are already able to get decent performance, then the extra cost of calculating event-type wise IRFs would be lower (of course, IRFs would still require more stats because you are dividing the sample by N, but cuts won't be that hard anymore so more events will survive). If we need enormous statistics, then it might even be unfeasible. 

For the ICRC we don't really need a very extensive study, but at least make sure with the MCs we have to be able to leave enough MCs for calculating the IRFs (which cannot be the same used to train/test/optimize the algorithms).

**Comment by orelgueta** [comment]
I trained the MLP_small model using various fractions for the training statistics, plot with results below (the legend states the test dataset size in %).

It looks like the default I chose arbitrarily of 25% training statistics in each energy bin is coincidently the fraction where performance saturates. We don't gain much by using more than 25% in the training sample. If we go down to 15% we don't lose much as well, so perhaps it is worth doing. We will see once we calculate the IRFs and look at the statistical uncertainties there.

![scores_features_1](https://user-images.githubusercontent.com/22728856/106959683-4ac3a800-673b-11eb-9a42-480b02c114ce.png)

**Comment by TarekHC** [comment]
Awesome. I would leave the 25% then (and close this issue!). 

Just for discussion: in this study I would have personally left "frozen" then test sample (perhaps a fixed 20% with exactly always the same events). This would of course have limited meaning at high energies, where you probably need more stats... But on the other hand you make sure that the different performance is 100% associated to the different training statistics (because the test events are identical).

But the method you followed is of course valid too, and the results super clear... So I'm very happy to close this issue!

**Comment by orelgueta** [comment]
> Just for discussion: in this study I would have personally left "frozen" then test sample (perhaps a fixed 20% with exactly always the same events). This would of course have limited meaning at high energies, where you probably need more stats... But on the other hand you make sure that the different performance is 100% associated to the different training statistics (because the test events are identical).

I thought about that, but since the test samples are statistically independent from the training ones, I was pretty confident that this approach would be equivalent. I chose to do it this way cause I also took the opportunity to implement a simpler way to have separate test samples per model (like I need for classification).

Either way, I agree that the results are clear enough to close this issue and stick with 25%. We will see when we produce IRFs how much pressure this loss of events puts on us.

**Comment by TarekHC** [comment]
> Either way, I agree that the results are clear enough to close this issue and stick with 25%. We will see when we produce IRFs how much pressure this loss of events puts on us.

Absolutely agree!
