### ISSUE TITLE
Compare models when training with all offset angles

### ISSUE THREAD

**Issue by orelgueta** [cta-observatory/iact_event_types#47]
Now that we are training a sample with all offset angles I played around with the different models to see which one performs best. The plots below are all using 25% of the sample as training sample. A separate study will look into reducing or increasing that fraction. Out of the many models tested, I selected a few and produced the summary plots below in order to justify the final choice.

First we start with various hyperparameter options using random forest. The first number in the title is the number of trees and the second is the tree maximum depth. This set of forests is after some optimisation, the original set of hyperparameters performed significantly worse. So in the plot below we can see that we more or less reached an optimum and regardless of which set of parameters we choose (except the 2000/5 forest).

![scores_features_1](https://user-images.githubusercontent.com/22728856/189626725-07e543fb-84a7-43a9-83d4-8ad1483a3efe.png)

Therefore, in the next comparison we chose the 300/15 one since it is the smallest (also in disk space).
Next we compare the random forest performance to the various MLP options.

![scores_comparison_1](https://user-images.githubusercontent.com/22728856/189637381-e22b2bce-5d38-4c3d-9c5e-6dc8c7fdf7a1.png)

Again, these models are after a first round of optimisation. Generally it is clear that either of the the three MLP_tanh, MLP_logistic, MLP_uniform would be good. They all provide equivalent performance. I suggest we keep MLP_tanh for the future just because it is the one we used in the past. All future tests should be performed with it.

**Comment by TarekHC** [comment]
Given that @JBernete found that MLP_tanh is also performing better than others, lets also close this issue. 

We can re-open it if we apply a significant change to the training (new features, or God knows what).
