### ISSUE TITLE
Separate tree for cuts?

### ISSUE THREAD

**Issue by orelgueta** [cta-observatory/iact_event_types#7]
The fact the the cuts are saved in a separate tree means it's harder to read the tree in batches as they recommend in the uproot docs. Is there anything we can do or do we need to hack it to work (or continue using arrays)?

**Comment by TarekHC** [comment]
After what you discussed with Gernot. Is there any conclusion on this? Can we simply close it assuming this won't be an issue? Or perhaps we need a step before preparing the input dataset?

**Comment by orelgueta** [comment]
We can probably close it. Not because it's not an issue, but because I don't expect it to be resolved at the input dataset level. We might need a pre-processing step to reduce and select the data, add a true event class column(s) and save in an easier format, but that I will leave to a separate issue when we get there.
